### ISSUE TITLE
check newly entered papers!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#295]
@DarwinSodhi @DeirdreLoughnan @cchambe12 @dbuona Hi all! I have added cleaning assignments to this file: data/ospree_2019update.xlsx 

Check for your initials and make comments here! I think all but Darwin's data are uploaded to review.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan @kfslimon had some good comments on your paper entry. Could you review and update/fix or ... if not, explain why not:

**Comments/Questions for Fu19**

1. Error in the taxon.notes column under the study tab:

The paper describes them as ‘saplings ~1.5 m’, in the study tab sapling is mistyped as ‘sampling’

2. For the daylength,forcing column under the study tab and photoperiod_day in data_detailed:

The paper describes two treatments: ambient, and two hours less than ambient (ambient-2). It is recorded as ‘ambient, -2’  in the study tab and either ‘ambient’ or ‘short’ in the data detailed tab. Recommend to changing to something like ‘ambient, ambient-2’ uniformly

3. Add ‘ambient’ for the temp.chilling column in the study tab

4. Add a clearer note that climate controlled chambers increased temperature uniformly by +0, +1, +2, +3,+4,+5.

5. In the data detailed tab the chilling columns should be filled out:

‘yes’ for field chill

1-Jan-2016 for fieldsample date (all rows)

‘ambient’ for chilling temperature

6. Missing a ‘1’ in the response column starting in row 30 of data_detailed

7. The chilling hour information should be added to the ‘field.chill.units’ and ‘cu.model’ columns according to this information from the paper:  ‘The chilling hours were summed when the hourly temperature was between 0 and 5°C from 1 September 2015 until the date of leaf‐out following previous study’

8. The fist set of data scraped in data_detailed looks like its from figure 3, but says figure ‘S1’

9.  Figure 2a is leafout date vs mean temp during the experimental period (forcing temp), the data scraped from this does not match the other forcing temps recorded in the same experiment, consider looking this over and deciding which values were the actual forcing temperatures.

**Comment by lizzieinvancouver** [comment]
@cchambe12 @kfslimon had some comments on your data entry. Can you either fix/address them or explain why not?

**Comments/Questions for richardson18**


1.  Add ‘5’ to Nlevels.chilling  and Nlevels.forcing column 

2. My take on the paper is that the trees did spend the winter in the field so there would be filed chilling, given that I would:

-Add ‘ambient’ to chillphotoperiod and daylength.chilling
-Add ‘yes’ to fieldchill

3. Error bars were not scraped the error type is described as ‘Error bars indicate 95% confidence interval’

4. Only one species was described, Larix laricina as well as understory shrub species were in the paper but not in the scraped data.

**Comment by dbuona** [comment]
@DarwinSodhi I just realized I didn't enter my error bars either for Fu18...I will do so now and push my changes so hold off for a few before you check this paper...thanks!

**Comment by dbuona** [comment]
@dbuona okay, Fu18 is should be good. thanks for waiting

**Comment by dbuona** [comment]
sorry the above @ should have been @DarwinSodhi

**Comment by dbuona** [comment]
@m-yasutake Here are my thoughts for prevey18:
field.sample.date: should be reentered in an unambiguous format (dd-Mon-yyyy)

material: I think it would be just cuttings but maybe okay as you have it

respvar should be daystoflowering not budburst

chilltemp: this is a tricky one, because for some the actual chilling treatment is "ambient", but  the paper reports a mean temperature, and that is the value reported in. @lizzieinvancouver, is there a better way to signify this? Having seen how our cleaning works, I think it would treat the average as a treatment.

Chilldays, if not specified, I think we would leave blank rather than "variable" or "ambient"

other than that I think it looks good.

**Comment by dbuona** [comment]
@DeirdreLoughnan @m-yasutake for vitra17
n: should be 5 except for 4 for prunus. Other than that seems good.

**Comment by cchambe12** [comment]
@kfslimon I addressed the issues mentioned for richardson18! Except I could not add the details for shrubs since the figure does not distinguish between species. Thanks!

**Comment by DarwinSodhi** [comment]
@dbuona 1. on the study tab exp 2 should say ambient, ambient -1 and ambient +1
2. How did you get provenance for the fagus species?
3. respvar should say daystosenescence 
4. growing lat/long is missing 
5. error bars are still missing on my version

**Comment by DarwinSodhi** [comment]
@kfslimon for Ramos et al. 2017 some of the resp_error have NA's while some have 0 but it isn't entirely clear to me how they were distinguished. 
But other than that, the paper looks entered well considering all the complexities, good job!

**Comment by DarwinSodhi** [comment]
@cchambe12 my data has been entered as of a few hours ago!

**Comment by cchambe12** [comment]
@DarwinSodhi I have a few things...

More nit-picky for cleaning later:
1. Could you remove the degree symbols from chilltemp
2. And make year just 2014, it makes it easier for calculating field chilling later
3. Could you change fieldsampledate format to dd-Mon-yyyy? It looks like you may have to change the entire column format
4. You have extra columns and rows at the end, could you delete these?
5. respvar should be 'daystobudburst' or 'percentbudburst' (no capital letters) - not numbers!
6. I'm not sure what 0 or AB means for respvar
7. For daystobudburst respvars, the response should be 1. For percentbudburst it should be the percent (minus the percent sign)

Man2017: This is a tough paper!
1. I think the chilltemp you listed is actually the forcing temperature. So you should move the 15day/5night to forcetemp and the chillphotoperiod of 14 to photoperiod_day (which would mean photoperiod_night would be 10). 
2. This is a weinberger experiment so there should be multiple field sample dates! 
3. The respvar should be thermaltimetodays instead of daystobudburst 
4. The response.time values for the percentbudburst figure seem very high. 
5. Adjust the study tab after taking into consideration these changes. There should be more Nlevels of chilling since they use the weinberger method. 

Malyshev18:
1. Just change year to 2013
2. Make sure you adjust respvar, response, response.time accordingly. Respvar should be daystobudburst, response should be 1 and then response.time should be days

These were tough papers!! Good work getting through them!

**Comment by cchambe12** [comment]
@dbuona I think you are checking the flynn18 entries? If so, I just added them. I used an R script which you can find in ospree/data/update2019/addinflynndata.R. Thanks, Dan!

**Comment by DarwinSodhi** [comment]
@cchambe12 Thanks for your feedback! I don't quite get you number 3 comment for Man2017 as the respvar is actually percentbudburst not daystobudburst! AB and 0 are the percentbudburst because they don't give values for AB which stands for Abnormal!

**Comment by cchambe12** [comment]
@DarwinSodhi Ahh I see yes it is only percentbudburst, sorry about that! The response.times are very high though. They should be 0-100 if the respvar is percentbudburst. Are the response.times in gdds? Or maybe even growing degree hours?

**Comment by dbuona** [comment]
@cchambe12 the flynn data and code look good to me. In fact, the code seems quite elegant.

**Comment by cchambe12** [comment]
@DarwinSodhi okay, so I would scrape Fig2 and have the respvar be thermaltimetohours and report the raw values for the y-axis. As we discussed, the right most point will be the first fieldsample.date and then each point further left will be the next fieldsample.date and so on. Good luck! Such a painful one! Let me know if you have more questions

**Comment by DarwinSodhi** [comment]
@cchambe12 I made the changes could you double-check I did it correctly, just to put my perfectionism at ease.

**Comment by cchambe12** [comment]
@DarwinSodhi so fast!! Okay just a couple of minor things, response should be changed to 1 now instead of percentbudburst and then you have thermaltimetodays as the respvar -- which is fine! -- but the units of your response.time are in hours. So I would either divide your response.time column by 24 to convert to days or change your thermaltimetodays to thermaltimetohours. Great work!!

**Comment by DarwinSodhi** [comment]
@cchambe12 Thanks for your help!

**Comment by lizzieinvancouver** [comment]
@dbuona @cchambe12 @DeirdreLoughnan @DarwinSodhi  Once you have put up a new xlsx file of your entered data (@DeirdreLoughnan can you reply for Kelley and Mika's work also) and gotten it signed off on by your reviewer, please add a note to this issue such as:

@lizzieinvancouver My xlsx data file is ready to go!

Once I have this from everyone I will close the issue. Thanks!

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver My xlsx data file is ready to go!

**Comment by DarwinSodhi** [comment]
@dbuona your changes look good!

**Comment by cchambe12** [comment]
@lizzieinvancouver all ready to go!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I uploaded my xlsx file and revised files for both ks and my

**Comment by lizzieinvancouver** [comment]
@dbuona Did you upload a final file for your data? Once that's done, we're good to go...

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan I just noticed a number of the fieldsample dates in ospree_2019update_ks.xlsx are listed without year ... can you check and update? Thanks!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver the ramos17 paper does not say what year the data was collected and Kelley has not received a reply to her email to the authors (#294)

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Yes, I forgot that -- but the way the dates are entered now it's not that there's truly no year (there is, it's 2019), you've just changed the Excel formatting to hide the year. I would put in a best-guess-placeholder-year for now and correct the formatting.

**Comment by dbuona** [comment]
My data is good to go!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I added years for ramos17. According to their email, the years of study were 1996, 1997, and 1998, but there should be four years. I assumed they started Oct 1995 and finished Feb 1998, would you agree? I also corrected some of the dates and was wondering if the last sampling date for exp 1 should actually be March 7, as stated in the caption.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Copying your message to issue #294

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi There is a bunch of numbers in columns BF-BT in your ospree_2019update_DSS.xlsx file ... are these important numbers or stuff that belongs in the scratch tab?

**Comment by DarwinSodhi** [comment]
@lizzieinvancouver these are numbers that belong in the scratch tab!

**Comment by lizzieinvancouver** [comment]
@DarwinSodhi Awesome -- thanks!

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan @DarwinSodhi @cchambe12 @dbuona 
Please review this issue and check that:

1. All the data you entered has been checked by someone else and ...
2. all the checks/fixes requested you have done. 
3. All the checks/fixes you requested of someone else's data have been done.

If you agree this is all done for all four of you, please close at next meeting!

**Comment by cchambe12** [comment]
All good to go!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I have checked MY and SL data as well. There are some discrepancies between what is in ospree_2019update_my and the new ospree2019_goo, including the date format and the name of the respvar.

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Needs to check ospree_2019update_my versus ospree2019_goo -- ospree_2019update_my is correct, need to make sure these corrections are carried through!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver after speaking with Cat, I realized I was looking at the wrong file. The ospree_2019update file that is in the analyses/output folder is correct. The ospree_2019update_goo file that is in the analysis/input folder is not. Sorry for the confusion.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan .. okay, can you check if ospree2019_goo is tracked? I don't see it in this repo ....
