### ISSUE TITLE
Simulate data similar to OSPREE to understand effects within subject centering

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#352]

**Comment by dbuona** [comment]
@AileneKane   I just pushed a simulation for within-group centering (wgc). for the most part, the wgs models come out with the same or very similar estimates as the non-wgs models, which surprised me (I expect the wgs models to be worse). The code is in analyses/bb_analysis/withingroupcenter_fake.R-- if you want to take a look and make sure it matches your understanding of what wgc is. I was lazy and ran things in lme4, but could redo them baysian if needed.

**Comment by AileneKane** [comment]
@dbuona Thank you for your work on this! A couple of requests/thoughts:
1) The models you ran are all get singular fit warmings. That means the model has as many parameters as the data, so there is no variation in random effects or anything else. I think that's why the estimates are the same across all the models. Perhaps you need to add more studies to your simulated data? Or fewer parameters to the model? Or maybe treatments is fitting as a factor instead of as a continuous variable, which is what it should be.
2) Your tru model isn't quite what I was thinking, but maybe its the same or better. I was thinking of a nonhierarchical model, in which one study had all treatments. Coudl you try that?

Thank you! Let me know if you want to talk through anything!

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona Acting in opposition to my own strong advice -- but based on Dan and Andrew's views -- I just uploaded cheap ugly code (models_stan_wgc.R) that I think does within-group-centering (I did it on our complex, as I am pretty sure this is how we should apply it given our model and all the decisions that went into that model) on the predictors and it gives basically identical answers except the intercept (mu and sigma) now look more like the z-score model:

```
> m2lni.sum[grep("mu_", rownames(m2lni.sum)),]
                    mean     se_mean        sd       2.5%        25%        50%
mu_a_sp       30.3152369 0.022542108 1.7900639 26.8122844 29.1098269 30.2944173
mu_b_force_sp -0.7919327 0.002947649 0.2038792 -1.1878573 -0.9246089 -0.7887558
mu_b_photo_sp -0.5031678 0.003552351 0.2128992 -0.9267925 -0.6450607 -0.5010869
mu_b_chill_sp -2.6922862 0.007693943 0.4955613 -3.6652888 -3.0204001 -2.6826974
                     75%       97.5%    n_eff      Rhat
mu_a_sp       31.4618221 33.91518955 6305.914 0.9994110
mu_b_force_sp -0.6577843 -0.39418031 4784.036 1.0000909
mu_b_photo_sp -0.3567107 -0.09949696 3591.833 1.0001996
mu_b_chill_sp -2.3671458 -1.75694123 4148.554 0.9993583
> m2lni.sum[grep("sigma_", rownames(m2lni.sum)),]
                       mean     se_mean        sd       2.5%        25%
sigma_a_sp       10.1494551 0.016413407 1.2963756  7.8700411  9.2481256
sigma_b_force_sp  1.0208708 0.003576952 0.1812351  0.7177356  0.8930004
sigma_b_photo_sp  0.8724001 0.004494499 0.1870523  0.5590419  0.7379949
sigma_b_chill_sp  2.3015037 0.007943549 0.4039536  1.6299296  2.0163226
sigma_y          15.5826179 0.002766830 0.2769259 15.0493979 15.3984740
                        50%        75%     97.5%     n_eff      Rhat
sigma_a_sp       10.0450998 10.9435356 12.898599  6238.270 0.9994849
sigma_b_force_sp  1.0044795  1.1286924  1.423296  2567.192 1.0006633
sigma_b_photo_sp  0.8547085  0.9845075  1.281645  1732.061 1.0025369
sigma_b_chill_sp  2.2525842  2.5418920  3.201049  2586.032 1.0012015
sigma_y          15.5797464 15.7618734 16.129100 10017.569 0.9992034
```

Maybe we can add a table to the supp with these results and call it a day?

**Comment by AileneKane** [comment]
Wow @lizzieinvancouver! Thanks! That's great! Yes, I'll add a table of those results and call it good!
Thank you @dbuona  for your work, too!

**Comment by lizzieinvancouver** [comment]
@dbuona Do you know if in the van de Pol paper the partial pooling is ONLY on the intercept? (I still can't see through this problem, even for observational data (unless, perhaps you pool on only intercepts and not slopes.)
@AileneKane Maybe best not to add to supp ... as it is so similar to our other models. See my edits in letter (will push final updates if my internet holds up, depends on the wind).

**Comment by AileneKane** [comment]
that's a good question about intercepts vs slopes, @lizzieinvancouver 
also, @dbuona in my earlier note (1.) I should have said "When I ran your models, I got singular fit warnings" Did you get those too or did i do something wrong?

**Comment by dbuona** [comment]
@lizzieinvancouver yes, the van de pol paper only uses varying intercept models...but in the last paragraph they say something like " the next step is to apply this method to varyibg-slope models, which should also be helpful" (paraphrased).
@AileneKane yes I did get singular fits for many of the models. I can try to complicated them, and run the base model you described

**Comment by AileneKane** [comment]
@lizzieinvancouver I'm making these tables for the suppand could not find a file you use in the code: bbstan_mainmodel_countinxns_datasetIDs.csv
could you push it, or is it something i should generate for myself using the countintxns code?

**Comment by lizzieinvancouver** [comment]
@AileneKane I forgot to push it! I am sorry! Pushed now, and I will make a note to try to double-check that code too.

**Comment by AileneKane** [comment]
Thanks for all your work on this! I think we're good to close it now!
