### ISSUE TITLE
date wrong for charrier11?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#403]
Paper says ...

> Bud growth during ecodormancy
> Bud growth rates were evaluated after endodormancy was broken under natural conditions (29 January [2009]). Single-bud cuttings (see above) were placed under long-day conditions at different temperatures (5, 10, 15, 20 and 25°C) and checked for burst every 2 days. MTB was calculated for each genotype and temperature.

But we entered "29 November 2008" which is the date for the chilling and heat requirements study.

Much check!

**Comment by md-garner** [comment]
@lizzieinvancouver Yes, it should be 29 Jan 2009. What script does this need to be corrected in?

**Comment by DeirdreLoughnan** [comment]
@md-garner I have been making my edits in analyses/cleaning.clean_misc.R.

**Comment by md-garner** [comment]
Thank you! I added the fix.

**Comment by lizzieinvancouver** [comment]
@md-garner @DeirdreLoughnan Thank you!!!

**Comment by lizzieinvancouver** [comment]
> Thank you! I added the fix.

@md-garner There's actually two experiments, do you know which one this goes with?

Also your code did not work so I commented it out (20882104d4ab0bf57d96bbff2a2aea0262a34c24). I will follow up and see if we can fix this another way.

**Comment by lizzieinvancouver** [comment]
@cchambe12 @AileneKane Can one of your help me with this? We're trying to run down what might be an error but I am not sure. @md-garner tried to help fix it but when I checked her code I found it did not work because the date is not in the original charrier data... see here from just the raw ospree data:

```
> d$fieldsample.date[d$datasetID=="charrier11"]
 [1] "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
[35] "" "" "" "" "" "" "" "" "" "" "" ""

```
But it appears in the cleaned data:
```
> d <- read.csv("~/Documents/git/projects/treegarden/budreview/ospree/analyses/output/ospree_clean_withchill.csv")
> d$fieldsample.date[d$datasetID=="charrier11"]
 [1] "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008"
 [8] "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008"
[15] "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008"
[22] "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008" "29-Nov-2008"
[29] "29-Nov-2008" "29-Nov-2008" ""            ""            ""            ""            ""           
[36] ""            ""            ""            ""            ""            ""            ""           
[43] "" 
```

I chased it to chilltemp code (see [here](https://github.com/lizzieinvancouver/ospree/blob/817c6161d7292fb1bff38273367bb18411765303/analyses/chilling/cleaning_chilltemp.R#L15)) which is where I think we should fix it but could use a second opinion. Thank you!

**Comment by md-garner** [comment]
@lizzieinvancouver It should go with exp 2, the one with different forcing treatments.

**Comment by cchambe12** [comment]
@lizzieinvancouver @md-garner  this fixed the date for exp2 but we're still missing chilling because we don't have a provenance.long entry for charrier11 exp 2. I can't get access to the paper, could someone send along the provenance.long for exp2 and then I can rerun all the code again?

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thanks for your help on this. I think the is the relevant text:

> Trees were between 15 and 20 years old and planted in two different locations in the middle of France: Crouël (Lowland: 03°08′50′′E, 45°46′20′′N, alt: 340 m) and Theix (Mountain: 03°01′00′′E, 45°43′10′′N, alt: 880 m). The two locations are 20 km apart and exhibit a mean difference in temperature of 3°C (Poirier et al. 2010). In the lowland orchard, fruit-oriented trees, Juglans regia L.

And I will email you the paper now.

**Comment by cchambe12** [comment]
Okay this has all been cleaned and is now working, we can close this issue!
